# Generated by Django 4.2.5 on 2023-09-25 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=64, unique=True, verbose_name='Идентификатор')),
                ('text', models.TextField(verbose_name='Описание урока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации продукта')),
                ('video_url', models.URLField(help_text='Ссылка на видео', unique=True, verbose_name='Ссылка на видео')),
                ('video_duration', models.DurationField(verbose_name='Длительность видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'Список уроков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=64, unique=True, verbose_name='Идентификатор')),
                ('text', models.TextField(verbose_name='Описание продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации продукта')),
                ('lessons', models.ManyToManyField(to='product.lesson', verbose_name='Уроки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Список продуктов',
                'ordering': ['name'],
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted', models.BooleanField(default=False, verbose_name='Доступ разрешен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'доступ',
                'verbose_name_plural': 'Список доступов',
                'ordering': ['-product'],
            },
        ),
    ]
