# Generated by Django 4.2.5 on 2023-09-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='product.lesson', verbose_name='Уроки'),
        ),
    ]
