# Generated by Django 4.2.5 on 2023-09-25 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_alter_product_name_alter_access_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='last_viewed_dDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего просмотра'),
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together={('user', 'product', 'lesson')},
        ),
    ]
